"use client";

import { motion } from "framer-motion";
import { Separator } from "@/components/ui/separator";

/* ------------------------------------------------------------------ */
/*  ANIMATION HELPERS                                                  */
/* ------------------------------------------------------------------ */
const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.5, ease: "easeOut" },
  }),
};

/* ------------------------------------------------------------------ */
/*  SECTIONS                                                           */
/* ------------------------------------------------------------------ */
const sections = [
  {
    heading: "Acceptance of Terms",
    body: `By accessing or using Nectar Engine (the "Product"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Product. These Terms apply to all visitors, users, and others who access or use the Product.`,
  },
  {
    heading: "Description of Product",
    body: `Nectar Engine is a digital content architecture tool. It provides structured templates, reference data, and sample outputs designed to assist users in creating affiliate marketing content. The Product generates static content toolkits based on user-provided input. It does not post, publish, or distribute content on any platform on the user's behalf.`,
  },
  {
    heading: "Use License",
    body: `Upon purchase, you are granted a non-exclusive, non-transferable, non-sublicensable license to use Nectar Engine for personal or internal business purposes. You may not: (a) resell, redistribute, lease, or sub-license the Product; (b) reverse-engineer, decompile, or disassemble any part of the Product; (c) use the Product to generate content for illegal purposes or in violation of any third-party platform's terms of service.`,
  },
  {
    heading: "User Responsibilities",
    body: `You are solely responsible for all content you create, modify, or publish using outputs generated by Nectar Engine. This includes but is not limited to: (a) verifying that all content complies with the current terms of service, advertising policies, and community guidelines of every platform where you intend to post; (b) ensuring compliance with applicable federal, state, and international laws, including FTC disclosure requirements; (c) reviewing and editing all generated content before publication; (d) maintaining awareness of changes to platform policies and network rules, as the Product's reference data reflects policies as of 2025 and does not update automatically.`,
  },
  {
    heading: "No Guarantee of Compliance Outcomes",
    body: `Nectar Engine provides reference data and content templates for educational and strategic purposes. It does not guarantee that any content generated with or without the Product will comply with any platform's policies, network rules, or applicable law. Platform terms of service change without notice, and enforcement is applied at each platform's sole discretion. The inclusion of a compliance reference matrix does not constitute legal advice. You should consult a qualified attorney for compliance questions specific to your use case.`,
  },
  {
    heading: "Intellectual Property",
    body: `The Product, including its design, code, reference data, documentation, and sample outputs displayed within the Product interface, is the intellectual property of Nectar Engine and is protected by applicable copyright and trademark law. Content generated by the Product based on your input is yours to use, edit, and publish at your discretion, subject to the responsibilities outlined above.`,
  },
  {
    heading: "Limitation of Liability",
    body: `To the maximum extent permitted by law, Nectar Engine shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising out of or related to your use of the Product. This includes damages resulting from content you publish using outputs generated by the Product, regardless of whether such content is edited or unedited.`,
  },
  {
    heading: "Disclaimer of Warranties",
    body: `The Product is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Product will be error-free, uninterrupted, or meet your specific requirements.`,
  },
  {
    heading: "Governing Law",
    body: `These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising from these Terms or your use of the Product shall be resolved through good-faith negotiation or, if necessary, in a court of competent jurisdiction.`,
  },
  {
    heading: "Changes to Terms",
    body: `We reserve the right to modify these Terms at any time. Material changes will be communicated through the Product or by email if contact information is provided. Continued use of the Product after changes are posted constitutes acceptance of the revised Terms.`,
  },
];

/* ------------------------------------------------------------------ */
/*  PAGE                                                               */
/* ------------------------------------------------------------------ */
export default function TermsPage() {
  return (
    <>
      <section className="mx-auto max-w-3xl px-4 sm:px-6 py-16 sm:py-24">
        <motion.p
          className="font-mono text-xs tracking-widest uppercase text-electric mb-4"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
        >
          Legal
        </motion.p>

        <motion.h1
          className="text-3xl sm:text-4xl font-bold tracking-tight mb-4"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          Terms of Service
        </motion.h1>

        <motion.p
          className="text-sm text-muted-foreground leading-relaxed mb-8"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          Last updated: 2025
        </motion.p>

        <Separator className="bg-border/60 mb-10" />

        <div className="space-y-10">
          {sections.map((section, i) => (
            <motion.div
              key={section.heading}
              variants={fadeUp}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-40px" }}
            >
              <h2 className="text-lg font-bold tracking-tight mb-3">
                {section.heading}
              </h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {section.body}
              </p>
            </motion.div>
          ))}
        </div>
      </section>
    </>
  );
}
